module Tushare
  module Datayes
    HTTP_OK = 200
    HTTP_AUTHORIZATION_ERROR = 401
    HTTPS_URL = 'api.wmcloud.com'.freeze
    HTTPS_PORT = 443
    SUCCESS_CODE = 1
    BOND = '/api/bond/getBond.json?secID=%s&ticker=%s&field=%s'.freeze
    BONDCF = '/api/bond/getBondCf.json?secID=%s&ticker=%s&beginDate=%s&cashTypeCD=%s&endDate=%s&field=%s'.freeze
    BONDCOUPON = '/api/bond/getBondCoupon.json?secID=%s&ticker=%s&field=%s'.freeze
    BONDGUAR = '/api/bond/getBondGuar.json?secID=%s&ticker=%s&guarModeCD=%s&field=%s'.freeze
    BONDISSUE = '/api/bond/getBondIssue.json?secID=%s&ticker=%s&raiseModeCD=%s&field=%s'.freeze
    BONDOPTION = '/api/bond/getBondOption.json?secID=%s&ticker=%s&field=%s'.freeze
    BONDRATING = '/api/bond/getBondRating.json?secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    EQU = '/api/equity/getEqu.json?equTypeCD=%s&secID=%s&ticker=%s&listStatusCD=%s&field=%s'.freeze
    EQUALLOT = '/api/equity/getEquAllot.json?isAllotment=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    EQUDIV = '/api/equity/getEquDiv.json?eventProcessCD=%s&exDivDate=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    EQUINDUSTRY = '/api/equity/getEquIndustry.json?industry=%s&industryID=%s&industryVersionCD=%s&secID=%s&ticker=%s&intoDate=%s&field=%s'.freeze
    EQUIPO = '/api/equity/getEquIPO.json?eventProcessCD=%s&secID=%s&ticker=%s&field=%s'.freeze
    EQUREF = '/api/equity/getEquRef.json?secID=%s&ticker=%s&beginDate=%s&endDate=%s&eventProcessCD=%s&field=%s'.freeze
    EQURETUD = '/api/equity/getEquRetud.json?listStatusCD=%s&secID=%s&ticker=%s&beginDate=%s&dailyReturnNoReinvLower=%s&dailyReturnNoReinvUpper=%s&dailyReturnReinvLower=%s&dailyReturnReinvUpper=%s&endDate=%s&isChgPctl=%s&field=%s'.freeze
    EQUSPLITS = '/api/equity/getEquSplits.json?secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FUTU = '/api/future/getFutu.json?exchangeCD=%s&secID=%s&ticker=%s&contractObject=%s&field=%s'.freeze
    FUTUCONVF = '/api/future/getFutuConvf.json?secID=%s&ticker=%s&field=%s'.freeze
    GUARRATING = '/api/bond/getGuarRating.json?secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    IDX = '/api/idx/getIdx.json?secID=%s&ticker=%s&field=%s'.freeze
    IDXCONS = '/api/idx/getIdxCons.json?secID=%s&ticker=%s&intoDate=%s&intoDate=%s&isNew=%s&field=%s'.freeze
    ISSUERRATING = '/api/bond/getIssuerRating.json?secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MKTEQUD = '/api/market/getMktEqud.json?secID=%s&ticker=%s&tradeDate=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MKTFUTD = '/api/market/getMktFutd.json?secID=%s&ticker=%s&tradeDate=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MKTIDXD = '/api/market/getMktIdxd.json?indexID=%s&ticker=%s&tradeDate=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SECID = '/api/master/getSecID.json?assetClass=%s&cnSpell=%s&partyID=%s&ticker=%s&field=%s'.freeze
    FUND = '/api/fund/getFund.json?etfLof=%s&listStatusCd=%s&secID=%s&ticker=%s&category=%s&operationMode=%s&field=%s'.freeze
    FUNDNAV = '/api/fund/getFundNav.json?dataDate=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FUNDDIVM = '/api/fund/getFundDivm.json?dataDate=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FUNDDIV = '/api/fund/getFundDiv.json?secID=%s&ticker=%s&adjustedType=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FUNDASSETS = '/api/fund/getFundAssets.json?reportDate=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FUNDHOLDINGS = '/api/fund/getFundHoldings.json?reportDate=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&secType=%s&field=%s'.freeze
    FDMTBS = '/api/fundamental/getFdmtBS.json?reportType=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&publishDateBegin=%s&publishDateEnd=%s&field=%s'.freeze
    FDMTBSBANK = '/api/fundamental/getFdmtBSBank.json?reportType=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&publishDateBegin=%s&publishDateEnd=%s&field=%s'.freeze
    FDMTBSSECU = '/api/fundamental/getFdmtBSSecu.json?reportType=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&publishDateBegin=%s&publishDateEnd=%s&field=%s'.freeze
    FDMTBSINDU = '/api/fundamental/getFdmtBSIndu.json?reportType=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&publishDateBegin=%s&publishDateEnd=%s&field=%s'.freeze
    FDMTBSINSU = '/api/fundamental/getFdmtBSInsu.json?reportType=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&publishDateBegin=%s&publishDateEnd=%s&field=%s'.freeze
    FDMTCF = '/api/fundamental/getFdmtCF.json?reportType=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&publishDateBegin=%s&publishDateEnd=%s&field=%s'.freeze
    FDMTCFBANK = '/api/fundamental/getFdmtCFBank.json?reportType=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&publishDateBegin=%s&publishDateEnd=%s&field=%s'.freeze
    FDMTCFSECU = '/api/fundamental/getFdmtCFSecu.json?reportType=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&publishDateBegin=%s&publishDateEnd=%s&field=%s'.freeze
    FDMTCFINDU = '/api/fundamental/getFdmtCFIndu.json?reportType=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&publishDateBegin=%s&publishDateEnd=%s&field=%s'.freeze
    FDMTCFINSU = '/api/fundamental/getFdmtCFInsu.json?reportType=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&publishDateBegin=%s&publishDateEnd=%s&field=%s'.freeze
    FDMTIS = '/api/fundamental/getFdmtIS.json?reportType=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&publishDateBegin=%s&publishDateEnd=%s&field=%s'.freeze
    FDMTISBANK = '/api/fundamental/getFdmtISBank.json?reportType=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&publishDateBegin=%s&publishDateEnd=%s&field=%s'.freeze
    FDMTISSECU = '/api/fundamental/getFdmtISSecu.json?reportType=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&publishDateBegin=%s&publishDateEnd=%s&field=%s'.freeze
    FDMTISINDU = '/api/fundamental/getFdmtISIndu.json?reportType=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&publishDateBegin=%s&publishDateEnd=%s&field=%s'.freeze
    FDMTISINSU = '/api/fundamental/getFdmtISInsu.json?reportType=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&publishDateBegin=%s&publishDateEnd=%s&field=%s'.freeze
    FDMTEE = '/api/fundamental/getFdmtEe.json?reportType=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&publishDateBegin=%s&publishDateEnd=%s&field=%s'.freeze
    FDMTEF = '/api/fundamental/getFdmtEf.json?reportType=%s&secID=%s&ticker=%s&beginDate=%s&endDate=%s&forecastType=%s&publishDateBegin=%s&publishDateEnd=%s&field=%s'.freeze
    TRADECAL = '/api/master/getTradeCal.json?exchangeCD=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INDUSTRY = '/api/master/getIndustry.json?industryVersion=%s&industryVersionCD=%s&industryLevel=%s&isNew=%s&field=%s'.freeze
    FSTTOTAL = '/api/equity/getFstTotal.json?beginDate=%s&endDate=%s&exchangeCD=%s&field=%s'.freeze
    FSTDETAIL = '/api/equity/getFstDetail.json?secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MKTBLOCKD = '/api/market/getMktBlockd.json?secID=%s&ticker=%s&tradeDate=%s&assetClass=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    HKEQU = '/api/HKequity/getHKEqu.json?listStatusCD=%s&secID=%s&ticker=%s&field=%s'.freeze
    HKEQUCA = '/api/HKequity/getHKEquCA.json?secID=%s&ticker=%s&eventTypeCD=%s&field=%s'.freeze
    MKTREPOD = '/api/market/getMktRepod.json?secID=%s&ticker=%s&tradeDate=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MKTBONDD = '/api/market/getMktBondd.json?secID=%s&ticker=%s&tradeDate=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    EQUSHARE = '/api/equity/getEquShare.json?secID=%s&ticker=%s&beginDate=%s&endDate=%s&partyID=%s&field=%s'.freeze
    REPO = '/api/bond/getRepo.json?secID=%s&ticker=%s&field=%s'.freeze
    MKTHKEQUD = '/api/market/getMktHKEqud.json?secID=%s&ticker=%s&tradeDate=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TICKRTSNAPSHOT = '/api/market/getTickRTSnapshot.json?securityID=%s&field=%s'.freeze
    TICKRTSNAPSHOTINDEX = '/api/market/getTickRTSnapshotIndex.json?securityID=%s&field=%s'.freeze
    FUTURETICKRTSNAPSHOT = '/api/market/getFutureTickRTSnapshot.json?instrumentID=%s&field=%s'.freeze
    TICKRTINTRADAY = '/api/market/getTickRTIntraDay.json?securityID=%s&endTime=%s&startTime=%s&field=%s'.freeze
    BARRTINTRADAY = '/api/market/getBarRTIntraDay.json?securityID=%s&endTime=%s&startTime=%s&field=%s'.freeze
    BARHISTONEDAY = '/api/market/getBarHistOneDay.json?securityID=%s&date=%s&endTime=%s&startTime=%s&field=%s'.freeze
    BARHISTDAYRANGE = '/api/market/getBarHistDateRange.json?securityID=%s&startDate=%s&&endDate=%s&field=%s'.freeze
    FUTURETICKRTINTRADAY = '/api/market/getFutureTickRTIntraDay.json?instrumentID=%s&endTime=%s&startTime=%s&field=%s'.freeze
    FUTUREBARINDAY = '/api/market/getFutureBarHistOneDay.json?instrumentID=%s&date=%s&field=%s'.freeze
    FUTUREBARDATERANGE = '/api/market/getFutureBarHistDateRange.json?instrumentID=%s&startDate=%s&endDate=%s&field=%s'.freeze
    STOCKFACTORSONEDAY = '/api/market/getStockFactorsOneDay.json?tradeDate=%s&secID=%s&ticker=%s&field=%s'.freeze
    STOCKFACTORSDATERANGE = '/api/market/getStockFactorsDateRange.json?secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MKTFUNDD = '/api/market/getMktFundd.json?secID=%s&ticker=%s&tradeDate=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MKTFUTMTR = '/api/market/getMktFutMTR.json?secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MKTFUTMSR = '/api/market/getMktFutMSR.json?secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MKTFUTMLR = '/api/market/getMktFutMLR.json?secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FUNDETFPRLIST = '/api/fund/getFundETFPRList.json?secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FUNDETFCONS = '/api/fund/getFundETFCons.json?secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FUNDRATING = '/api/fund/getFundRating.json?secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINAMACRODATA = '/api/macro/getChinaMacroData.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINAMACROINFO = '/api/macro/getChinaMacroInfo.json?indicID=%s&indicNameAbbr=%s&parentID=%s&field=%s'.freeze
    GLOBALMACRODATA = '/api/macro/getGlobalMacroData.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    GLOBALMACROINFO = '/api/macro/getGlobalMacroInfo.json?indicID=%s&indicNameAbbr=%s&parentID=%s&field=%s'.freeze
    INDUSTRIALDATA = '/api/macro/getIndustrialData.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INDUSTRIALINFO = '/api/macro/getIndustrialInfo.json?indicID=%s&indicNameAbbr=%s&parentID=%s&field=%s'.freeze
    ECOMMERCEDATA = '/api/macro/getEcommerceData.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEINFO = '/api/macro/getEcommerceInfo.json?indicID=%s&indicNameAbbr=%s&parentID=%s&field=%s'.freeze
    MKTMFUTD = '/api/market/getMktMFutd.json?contractMark=%s&contractObject=%s&mainCon=%s&tradeDate=%s&endDate=%s&startDate=%s&field=%s'.freeze
    CHINADATAGDP = '/api/macro/getChinaDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATAECI = '/api/macro/getChinaDataECI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATAPMI = '/api/macro/getChinaDataPMI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATACCI = '/api/macro/getChinaDataCCI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATAECONOMISTSBOOMINDEX = '/api/macro/getChinaDataEconomistsBoomIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATAINDUSTRIALBUSINESSCLIMATEINDEX = '/api/macro/getChinaDataIndustrialBusinessClimateIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATACPI = '/api/macro/getChinaDataCPI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATAPPI = '/api/macro/getChinaDataPPI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATAINDUSTRY = '/api/macro/getChinaDataIndustry.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATARETAILSALES = '/api/macro/getChinaDataRetailSales.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATARESIDENTINCOMEEXP = '/api/macro/getChinaDataResidentIncomeExp.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATAFAI = '/api/macro/getChinaDataFAI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATAREALESTATE = '/api/macro/getChinaDataRealEstate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATAFOREIGNTRADE = '/api/macro/getChinaDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATAFDI = '/api/macro/getChinaDataFDI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATAMONEYSTATISTICS = '/api/macro/getChinaDataMoneyStatistics.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATAALLSYSTEMFINANCING = '/api/macro/getChinaDataAllSystemFinancing.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATALENDINGDEPOSIT = '/api/macro/getChinaDataLendingDeposit.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATACREDITFUNDSTABLE = '/api/macro/getChinaDataCreditFundsTable.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATAOPENMARKETOPERATION = '/api/macro/getChinaDataOpenMarketOperation.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATAEXCHANGERATE = '/api/macro/getChinaDataExchangeRate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATAINTERESTRATELENDINGDEPOSIT = '/api/macro/getChinaDataInterestRateLendingDeposit.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATAINTERESTRATESHIBOR = '/api/macro/getChinaDataInterestRateSHIBOR.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATAINTERESTRATEINTERBANKREPO = '/api/macro/getChinaDataInterestRateInterbankRepo.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATAFINANCE = '/api/macro/getChinaDataFinance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CHINADATAGOLDCLOSEPRICE = '/api/macro/getChinaDataGoldClosePrice.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    USDATAGDP = '/api/macro/getUSDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    USDATAFOREIGNTRADE = '/api/macro/getUSDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    USDATAPRICEINDEX = '/api/macro/getUSDataPriceIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    USDATAEMPLOYMENTUNEMPLOYMENT = '/api/macro/getUSDataEmploymentUnemployment.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    USDATAINTERESTRATE = '/api/macro/getUSDataInterestRate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    USDATAEXCHANGERATE = '/api/macro/getUSDataExchangeRate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    USDATAMONEYSUPPLY = '/api/macro/getUSDataMoneySupply.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    USDATACONSUMERCREDIT = '/api/macro/getUSDataConsumerCredit.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    USDATACLIMATEINDEX = '/api/macro/getUSDataClimateIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    USDATADURABLEGOODS = '/api/macro/getUSDataDurableGoods.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    USDATAREALESTATE = '/api/macro/getUSDataRealEstate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    USDATADOMESTICTRADE = '/api/macro/getUSDataDomesticTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    EUDATAGDP = '/api/macro/getEUDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    EUDATAFOREIGNTRADE = '/api/macro/getEUDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    EUDATAPRICEINDEX = '/api/macro/getEUDataPriceIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    EUDATAEMPLOYMENTUNEMPLOYMENT = '/api/macro/getEUDataEmploymentUnemployment.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    EUDATAINTERESTRATE = '/api/macro/getEUDataInterestRate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    EUDATAEXCHANGERATE = '/api/macro/getEUDataExchangeRate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    EUDATABANKING = '/api/macro/getEUDataBanking.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    EUDATACLIMATEINDEX = '/api/macro/getEUDataClimateIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    EUDATAINDUSTRY = '/api/macro/getEUDataIndustry.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    EUDATARETAIL = '/api/macro/getEUDataRetail.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SWITZERLANDDATAGDP = '/api/macro/getSwitzerlandDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SWITZERLANDDATAPRICEINDEX = '/api/macro/getSwitzerlandDataPriceIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SWITZERLANDDATACLIMATEINDEX = '/api/macro/getSwitzerlandDataClimateIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SWITZERLANDDATAMONEYSUPPLY = '/api/macro/getSwitzerlandDataMoneySupply.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SWEDENDATAGDP = '/api/macro/getSwedenDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SWEDENDATAPRICEINDEX = '/api/macro/getSwedenDataPriceIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SWEDENDATAFOREIGNTRADE = '/api/macro/getSwedenDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    KOREADATAGDP = '/api/macro/getKoreaDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    KOREADATAPRICEINDEX = '/api/macro/getKoreaDataPriceIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    KOREADATAEMPLOYMENTUNEMPLOYMENT = '/api/macro/getKoreaDataEmploymentUnemployment.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    KOREADATAINTERESTRATES = '/api/macro/getKoreaDataInterestRates.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    KOREADATAEXCHANGERATE = '/api/macro/getKoreaDataExchangeRate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    KOREADATAMONEYSUPPLY = '/api/macro/getKoreaDataMoneySupply.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    KOREADATACLIMATEINDEX = '/api/macro/getKoreaDataClimateIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    KOREADATA_EXTERNALDEBT = '/api/macro/getKoreaData_ExternalDebt.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    KOREADATAINDUSTRYANDSERVICE = '/api/macro/getKoreaDataIndustryandService.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    KOREADATAREALESTATE = '/api/macro/getKoreaDataRealEstate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    AUSTRALIADATAGDP = '/api/macro/getAustraliaDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    AUSTRALIADATAFOREIGNTRADE = '/api/macro/getAustraliaDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    AUSTRALIADATAPRICEINDEX = '/api/macro/getAustraliaDataPriceIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    AUSTRALIADATAEMPLOYMENT = '/api/macro/getAustraliaDataEmployment.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    AUSTRALIADATACLIMATEINDEX = '/api/macro/getAustraliaDataClimateIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ITALYDATAGDP = '/api/macro/getItalyDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ITALYDATAPAYMENTSBALANCE = '/api/macro/getItalyDataPaymentsBalance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ITALYDATAPRICEINDEX = '/api/macro/getItalyDataPriceIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ITALYDATAEMPLOYMENT = '/api/macro/getItalyDataEmployment.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ITALYDATAFINANCE = '/api/macro/getItalyDataFinance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ITALYDATACLIMATEINDEX = '/api/macro/getItalyDataClimateIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ITALYDATAINTERESTRATE = '/api/macro/getItalyDataInterestRate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SPAINDATAGDP = '/api/macro/getSpainDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SPAINDATAFOREIGNTRADE = '/api/macro/getSpainDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SPAINDATAPAYMENTSBALANCE = '/api/macro/getSpainDataPaymentsBalance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SPAINDATABANKING = '/api/macro/getSpainDataBanking.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SPAINDATATRANSPORTATION = '/api/macro/getSpainDataTransportation.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SPAINDATAENERGY = '/api/macro/getSpainDataEnergy.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SPAINDATAFINANCE = '/api/macro/getSpainDataFinance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CANADADATAGDP = '/api/macro/getCanadaDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CANADADATAPAYMENTSBALANCE = '/api/macro/getCanadaDataPaymentsBalance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CANADADATAFOREIGNTRADE = '/api/macro/getCanadaDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CANADADATAPRICEINDEX = '/api/macro/getCanadaDataPriceIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CANADADATABANKING = '/api/macro/getCanadaDataBanking.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CANADADATAEMPLOYMENT = '/api/macro/getCanadaDataEmployment.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CANADADATAMANUFACTURING = '/api/macro/getCanadaDataManufacturing.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CANADADATAREALESTATE = '/api/macro/getCanadaDataRealEstate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CANADADATACLIMATEINDEX = '/api/macro/getCanadaDataClimateIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    HKDATAGDP = '/api/macro/getHKDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    HKDATAFOREIGNTRADE = '/api/macro/getHKDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    HKDATAPRICEINDEX = '/api/macro/getHKDataPriceIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    HKDATAFINANCE = '/api/macro/getHKDataFinance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    HKDATABANKING = '/api/macro/getHKDataBanking.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    HKDATAINDUSTRY = '/api/macro/getHKDataIndustry.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    HKDATACONSUMPTION = '/api/macro/getHKDataConsumption.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    HKDATATHROUGHPUT = '/api/macro/getHKDataThroughput.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    HKDATAEMPLOYMENT = '/api/macro/getHKDataEmployment.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    HKDATAINTERESTRATE = '/api/macro/getHKDataInterestRate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    HKDATAEXCHANGERATE = '/api/macro/getHKDataExchangeRate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    HKDATAREALESTATE = '/api/macro/getHKDataRealEstate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    HKDATATOURISM = '/api/macro/getHKDataTourism.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INDIADATAGDP = '/api/macro/getIndiaDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INDIADATAPAYMENTSBALANCE = '/api/macro/getIndiaDataPaymentsBalance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INDIADATAPRICEINDEX = '/api/macro/getIndiaDataPriceIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INDIADATATOURISM = '/api/macro/getIndiaDataTourism.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INDIADATAENERGY = '/api/macro/getIndiaDataEnergy.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INDIADATACLIMATEINDEX = '/api/macro/getIndiaDataClimateIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INDIADATABANKING = '/api/macro/getIndiaDataBanking.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INDIADATAINDUSTRY = '/api/macro/getIndiaDataIndustry.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INDIADATAFOREIGNTRADE = '/api/macro/getIndiaDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MALAYSIADATAGDP = '/api/macro/getMalaysiaDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MALAYSIADATAPAYMENTSBALANCE = '/api/macro/getMalaysiaDataPaymentsBalance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MALAYSIADATAFOREIGNTRADE = '/api/macro/getMalaysiaDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MALAYSIADATAPRICEINDEX = '/api/macro/getMalaysiaDataPriceIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MALAYSIADATAEMPLOYMENT = '/api/macro/getMalaysiaDataEmployment.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MALAYSIADATAINDUSTRY = '/api/macro/getMalaysiaDataIndustry.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MALAYSIADATAFINANCE = '/api/macro/getMalaysiaDataFinance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MALAYSIADATAMONEYSUPPLY = '/api/macro/getMalaysiaDataMoneySupply.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MALAYSIADATAREALESTATE = '/api/macro/getMalaysiaDataRealEstate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INDONESIADATAGDP = '/api/macro/getIndonesiaDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INDONESIADATAPAYMENTSBALANCE = '/api/macro/getIndonesiaDataPaymentsBalance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INDONESIADATAFOREIGNTRADE = '/api/macro/getIndonesiaDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INDONESIADATAPRICEINDEX = '/api/macro/getIndonesiaDataPriceIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INDONESIADATAINDUSTRY = '/api/macro/getIndonesiaDataIndustry.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INDONESIADATAFINANCE = '/api/macro/getIndonesiaDataFinance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INDONESIADATABANKING = '/api/macro/getIndonesiaDataBanking.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INDONESIADATASECURITY = '/api/macro/getIndonesiaDataSecurity.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INDONESIADATATOURISM = '/api/macro/getIndonesiaDataTourism.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TURKEYDATAGDP = '/api/macro/getTurkeyDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TURKEYDATAPAYMENTSBALANCE = '/api/macro/getTurkeyDataPaymentsBalance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TURKEYDATAFOREIGNTRADE = '/api/macro/getTurkeyDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TURKEYDATAPRICEINDEX = '/api/macro/getTurkeyDataPriceIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TURKEYDATAEMPLOYMENT = '/api/macro/getTurkeyDataEmployment.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TURKEYDATAINDUSTRY = '/api/macro/getTurkeyDataIndustry.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TURKEYDATAFINANCE = '/api/macro/getTurkeyDataFinance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TURKEYDATAMONEYSUPPLY = '/api/macro/getTurkeyDataMoneySupply.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    THAILANDDATAGDP = '/api/macro/getThailandDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    THAILANDDATAPAYMENTSBALANCE = '/api/macro/getThailandDataPaymentsBalance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    THAILANDDATAFOREIGNTRADE = '/api/macro/getThailandDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    THAILANDDATAPRICEINDEX = '/api/macro/getThailandDataPriceIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    THAILANDDATAEMPLOYMENT = '/api/macro/getThailandDataEmployment.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    THAILANDDATAINDUSTRY = '/api/macro/getThailandDataIndustry.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    THAILANDDATAFINANCE = '/api/macro/getThailandDataFinance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    THAILANDDATACLIMATEINDEX = '/api/macro/getThailandDataClimateIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    THAILANDDATAMONEYSUPPLY = '/api/macro/getThailandDataMoneySupply.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    UKDATAGDP = '/api/macro/getUKDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    UKDATAFOREIGNTRADE = '/api/macro/getUKDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    UKDATACPI = '/api/macro/getUKDataCPI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    UKDATARPI = '/api/macro/getUKDataRPI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    UKDATAEMPLOYMENT = '/api/macro/getUKDataEmployment.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    UKDATAMONEYSUPPLY = '/api/macro/getUKDataMoneySupply.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    UKDATACONSUMERCREDIT = '/api/macro/getUKDataConsumerCredit.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    UKDATACLIMATEINDEX = '/api/macro/getUKDataClimateIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    UKDATAFINANCE = '/api/macro/getUKDataFinance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    UKDATAINDUSTRIALPI = '/api/macro/getUKDataIndustrialPI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    UKDATAHOUSEPI = '/api/macro/getUKDataHousePI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    UKDATAINTERESTRATES = '/api/macro/getUKDataInterestRates.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    UKDATAEXCHANGERATE = '/api/macro/getUKDataExchangeRate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    JAPANDATAGDP = '/api/macro/getJapanDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    JAPANDATAFOREIGNTRADE = '/api/macro/getJapanDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    JAPANDATACPI = '/api/macro/getJapanDataCPI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    JAPANDATAEMPLOYMENT = '/api/macro/getJapanDataEmployment.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    JAPANDATAMONEYSUPPLY = '/api/macro/getJapanDataMoneySupply.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    JAPANDATACLIMATEINDEX = '/api/macro/getJapanDataClimateIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    JAPANDATAINDUSTRIALPI = '/api/macro/getJapanDataIndustrialPI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    JAPANDATAHOUSEPI = '/api/macro/getJapanDataHousePI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    JAPANDATAINTERESTRATES = '/api/macro/getJapanDataInterestRates.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    JAPANDATAEXCHANGERATE = '/api/macro/getJapanDataExchangeRate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    GERMANYDATAGDP = '/api/macro/getGermanyDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    GERMANYDATAFOREIGNTRADE = '/api/macro/getGermanyDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    GERMANYDATACPI = '/api/macro/getGermanyDataCPI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    GERMANYDATAPPI = '/api/macro/getGermanyDataPPI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    GERMANYDATAIMPORTEXPORTPI = '/api/macro/getGermanyDataImportExportPI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    GERMANYDATAEMPLOYMENT = '/api/macro/getGermanyDataEmployment.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    GERMANYDATAMONEYSUPPLY = '/api/macro/getGermanyDataMoneySupply.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    GERMANYDATACLIMATEINDEX = '/api/macro/getGermanyDataClimateIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    GERMANYDATAFINANCE = '/api/macro/getGermanyDataFinance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    GERMANYDATAINDUSTRIALPI = '/api/macro/getGermanyDataIndustrialPI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    GERMANYDATAREALESTATE = '/api/macro/getGermanyDataRealEstate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    GERMANYDATADOMESTICTRADE = '/api/macro/getGermanyDataDomesticTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    GERMANYDATAINTERESTRATES = '/api/macro/getGermanyDataInterestRates.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FRANCEDATAFINANCE = '/api/macro/getFranceDataFinance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FRANCEDATAGDP = '/api/macro/getFranceDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FRANCEDATAFOREIGNTRADE = '/api/macro/getFranceDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FRANCEDATACPI = '/api/macro/getFranceDataCPI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FRANCEDATAPPI = '/api/macro/getFranceDataPPI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FRANCEDATAIMPORTPI = '/api/macro/getFranceDataImportPI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FRANCEDATAEMPLOYMENT = '/api/macro/getFranceDataEmployment.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FRANCEDATAMONEYSUPPLY = '/api/macro/getFranceDataMoneySupply.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FRANCEDATACLIMATEINDEX = '/api/macro/getFranceDataClimateIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FRANCEDATAINDUSTRIALPI = '/api/macro/getFranceDataIndustrialPI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FRANCEDATADOMESTICTRADE = '/api/macro/getFranceDataDomesticTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FRANCEDATAINTERESTRATES = '/api/macro/getFranceDataInterestRates.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TAIWANDATAGDP = '/api/macro/getTaiwanDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TAIWANDATAEXTERNALDEBT = '/api/macro/getTaiwanDataExternalDebt.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TAIWANDATAFOREIGNTRADE = '/api/macro/getTaiwanDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TAIWANDATACPI = '/api/macro/getTaiwanDataCPI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TAIWANDATAIMPORTEXPORTPI = '/api/macro/getTaiwanDataImportExportPI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TAIWANDATAEMPLOYMENT = '/api/macro/getTaiwanDataEmployment.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TAIWANDATAMONEYSUPPLY = '/api/macro/getTaiwanDataMoneySupply.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TAIWANDATALENDINGDEPOSIT = '/api/macro/getTaiwanDataLendingDeposit.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TAIWANDATARESERVEFUND = '/api/macro/getTaiwanDataReserveFund.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TAIWANDATACLIMATEINDEX = '/api/macro/getTaiwanDataClimateIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TAIWANDATAFINANCE = '/api/macro/getTaiwanDataFinance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TAIWANDATAINDUSTRIALPI = '/api/macro/getTaiwanDataIndustrialPI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TAIWANDATAREALESTATE = '/api/macro/getTaiwanDataRealEstate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TAIWANDATATOURISM = '/api/macro/getTaiwanDataTourism.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TAIWANDATACROSSSTRAITTRADE = '/api/macro/getTaiwanDataCrossStraitTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TAIWANDATABUSINESSANDECONOMY = '/api/macro/getTaiwanDataBusinessandEconomy.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TAIWANDATAINTERESTRATES = '/api/macro/getTaiwanDataInterestRates.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TAIWANDATAEXCHANGERATE = '/api/macro/getTaiwanDataExchangeRate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MACAODATAGDP = '/api/macro/getMacaoDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MACAODATAPRICEINDEX = '/api/macro/getMacaoDataPriceIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MACAODATAEMPLOYMENT = '/api/macro/getMacaoDataEmployment.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MACAODATAMONEYSUPPLY = '/api/macro/getMacaoDataMoneySupply.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MACAODATAFOREIGNEXCHANGERESERVES = '/api/macro/getMacaoDataForeignExchangeReserves.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MACAODATATOURISM = '/api/macro/getMacaoDataTourism.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MACAODATAGAMINGINDUSTRY = '/api/macro/getMacaoDataGamingIndustry.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MACAODATAINTERESTRATES = '/api/macro/getMacaoDataInterestRates.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MACAODATAEXCHANGERATE = '/api/macro/getMacaoDataExchangeRate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    RUSSIADATAGDP = '/api/macro/getRussiaDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    RUSSIADATAFOREIGNTRADE = '/api/macro/getRussiaDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    RUSSIADATACPI = '/api/macro/getRussiaDataCPI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    RUSSIADATAMONEYSUPPLY = '/api/macro/getRussiaDataMoneySupply.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    RUSSIADATACLIMATEINDEX = '/api/macro/getRussiaDataClimateIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    RUSSIADATAINTERESTRATES = '/api/macro/getRussiaDataInterestRates.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    RUSSIADATAEXCHANGERATE = '/api/macro/getRussiaDataExchangeRate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    BRAZILDATAGDP = '/api/macro/getBrazilDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    BRAZILDATAFOREIGNTRADE = '/api/macro/getBrazilDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    BRAZILDATAPRICEINDEX = '/api/macro/getBrazilDataPriceIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    BRAZILDATAEMPLOYMENT = '/api/macro/getBrazilDataEmployment.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    BRAZILDATAMONEYSUPPLY = '/api/macro/getBrazilDataMoneySupply.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    BRAZILDATACLIMATEINDEX = '/api/macro/getBrazilDataClimateIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    BRAZILDATARETAILSALE = '/api/macro/getBrazilDataRetailSale.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    BRAZILDATAINTERESTRATES = '/api/macro/getBrazilDataInterestRates.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    BRAZILDATAEXCHANGERATE = '/api/macro/getBrazilDataExchangeRate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SOUTHAFRICADATAGDP = '/api/macro/getSouthAfricaDataGDP.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SOUTHAFRICADATAEMPLOYMENTUNEMPLOYMENT = '/api/macro/getSouthAfricaDataEmploymentUnemployment.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SOUTHAFRICADATAFOREIGNTRADE = '/api/macro/getSouthAfricaDataForeignTrade.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SOUTHAFRICADATACPI = '/api/macro/getSouthAfricaDataCPI.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SOUTHAFRICADATAMONEYSUPPLY = '/api/macro/getSouthAfricaDataMoneySupply.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SOUTHAFRICADATACLIMATEINDEX = '/api/macro/getSouthAfricaDataClimateIndex.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SOUTHAFRICADATAINDUSTRY = '/api/macro/getSouthAfricaDataIndustry.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SOUTHAFRICADATAREALESTATE = '/api/macro/getSouthAfricaDataRealEstate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SOUTHAFRICADATARETAILSALES = '/api/macro/getSouthAfricaDataRetailSales.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SOUTHAFRICADATAINTERESTRATES = '/api/macro/getSouthAfricaDataInterestRates.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SOUTHAFRICADATAEXCHANGERATE = '/api/macro/getSouthAfricaDataExchangeRate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    AGRICDATAPRICE = '/api/macro/getAgricDataPrice.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    AGRICDATAOUTPV = '/api/macro/getAgricDataOutpV.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    AGRICDATAWASDE = '/api/macro/getAgricDataWASDE.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    AGRICDATAIMPTEXPT = '/api/macro/getAgricDataImptExpt.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FOODBVGDATAPRICE = '/api/macro/getFoodBvgDataPrice.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FOODBVGDATASALESOUTPUT = '/api/macro/getFoodBvgDataSalesOutput.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FOODBVGDATAIMPTEXPT = '/api/macro/getFoodBvgDataImptExpt.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    COMMTRADEDATATRSCG = '/api/macro/getCommTradeDataTRSCG.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    COMMTRADEDATASALES50LARGEEN = '/api/macro/getCommTradeDataSales50LargeEn.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    COMMTRADEDATAINDEXKEYCIRCEN = '/api/macro/getCommTradeDataIndexKeyCircEn.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CATERTOURDATATRSCG = '/api/macro/getCaterTourDataTRSCG.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CATERTOURDATAHOTELSOPER = '/api/macro/getCaterTourDataHotelsOper.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CATERTOURDATANEWHOTEL = '/api/macro/getCaterTourDataNewHotel.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CATERTOURDATAINBOUNDTOUR = '/api/macro/getCaterTourDataInboundTour.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    BIOMEDICINEDATASALESOUTPUT = '/api/macro/getBioMedicineDataSalesOutput.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    BIOMEDICINEDATAIMPTEXPT = '/api/macro/getBioMedicineDataImptExpt.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    PETROCHEMDATAPRICE = '/api/macro/getPetrochemDataPrice.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    PETROCHEMDATASALESOUTPUT = '/api/macro/getPetrochemDataSalesOutput.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    PETROCHEMDATAIMPTEXPT = '/api/macro/getPetrochemDataImptExpt.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CLOTHTEXDATAPRICE = '/api/macro/getClothTexDataPrice.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CLOTHTEXDATASALESOUTPUT = '/api/macro/getClothTexDataSalesOutput.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CLOTHTEXDATACOTTONWASDE = '/api/macro/getClothTexDataCottonWASDE.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    CLOTHTEXDATAIMPTEXPT = '/api/macro/getClothTexDataImptExpt.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    LIGHTMANUFDATAPRICE = '/api/macro/getLightManufDataPrice.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    LIGHTMANUFDATASALESOUTPUT = '/api/macro/getLightManufDataSalesOutput.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    LIGHTMANUFDATAIMPTEXPT = '/api/macro/getLightManufDataImptExpt.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MININGDATAPRICE = '/api/macro/getMiningDataPrice.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MININGDATAOUTPSALESTRANSP = '/api/macro/getMiningDataOutpSalesTransp.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MININGDATAIMPTEXPT = '/api/macro/getMiningDataImptExpt.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FERMETALDATAPRICE = '/api/macro/getFerMetalDataPrice.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FERMETALDATASALESOUTPUT = '/api/macro/getFerMetalDataSalesOutput.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    FERMETALDATAIMPTEXPT = '/api/macro/getFerMetalDataImptExpt.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    NONFERMETALDATAPRICE = '/api/macro/getNonferMetalDataPrice.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    NONFERMETALDATASALESOUTPUT = '/api/macro/getNonferMetalDataSalesOutput.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    NONFERMETALDATAIMPTEXPT = '/api/macro/getNonferMetalDataImptExpt.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    DELIVERYEQDATAPRICE = '/api/macro/getDeliveryEqDataPrice.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    DELIVERYEQDATASALESOUTPUT = '/api/macro/getDeliveryEqDataSalesOutput.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    DELIVERYEQDATAIMPTEXPT = '/api/macro/getDeliveryEqDataImptExpt.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TRAFFICTRANSDATARAILWAY = '/api/macro/getTrafficTransDataRailway.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TRAFFICTRANSDATAROAD = '/api/macro/getTrafficTransDataRoad.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TRAFFICTRANSDATAWATERWAY = '/api/macro/getTrafficTransDataWaterway.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TRAFFICTRANSDATAAIR = '/api/macro/getTrafficTransDataAir.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    UTILINDUSTRYDATAPOWER = '/api/macro/getUtilIndustryDataPower.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    UTILINDUSTRYDATAWATER = '/api/macro/getUtilIndustryDataWater.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    UTILINDUSTRYDATAGAS = '/api/macro/getUtilIndustryDataGas.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    UTILINDUSTRYDATAENVIRPROT = '/api/macro/getUtilIndustryDataEnvirProt.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ELECCOMPDATAPRICE = '/api/macro/getElecCompDataPrice.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ELECCOMPDATASALESOUTPUT = '/api/macro/getElecCompDataSalesOutput.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ELECCOMPDATAIMPTEXPT = '/api/macro/getElecCompDataImptExpt.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INFOEQPTDATAPRICE = '/api/macro/getInfoEqptDataPrice.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INFOEQPTDATASALESOUTPUT = '/api/macro/getInfoEqptDataSalesOutput.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INFOEQPTDATAIMPTEXPT = '/api/macro/getInfoEqptDataImptExpt.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    HOUSEHOLDAPLSDATASALESOUTPUT = '/api/macro/getHouseholdAplsDataSalesOutput.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    HOUSEHOLDAPLSDATAIMPTEXPT = '/api/macro/getHouseholdAplsDataImptExpt.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INFOSERVDATASOFTWARE = '/api/macro/getInfoServDataSoftware.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INFOSERVDATACOMM = '/api/macro/getInfoServDataComm.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INFOSERVDATAINTERNET = '/api/macro/getInfoServDataInternet.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    REALESTDATAPRICE = '/api/macro/getRealEstDataPrice.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    REALESTDATAINVESTDVPT = '/api/macro/getRealEstDataInvestDvpt.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    REALESTDATALAND = '/api/macro/getRealEstDataLand.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    REALESTDATASALES = '/api/macro/getRealEstDataSales.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    BLDGMATERDATAPRICE = '/api/macro/getBldgMaterDataPrice.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    BLDGMATERDATASALESOUTPUT = '/api/macro/getBldgMaterDataSalesOutput.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MCHNREQPTDATASALESOUTPUT = '/api/macro/getMchnrEqptDataSalesOutput.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MCHNREQPTDATAIMPTEXPT = '/api/macro/getMchnrEqptDataImptExpt.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    BANKDATAASSETSLIABILITIES = '/api/macro/getBankDataAssetsLiabilities.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    BANKDATANONPERFORMINGLOANS = '/api/macro/getBankDataNonPerformingLoans.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SECURITIESDATAOPERINDIC = '/api/macro/getSecuritiesDataOperIndic.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INSDATAPREMPRYINSURANCE = '/api/macro/getInsDataPremPryInsurance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INSDATACLAIMPAYMENT = '/api/macro/getInsDataClaimPayment.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INSDATAFUNDBALANCE = '/api/macro/getInsDataFundBalance.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    INSDATAASSETS = '/api/macro/getInsDataAssets.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAYILI = '/api/macro/getEcommerceDataYili.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAGUANGMING = '/api/macro/getEcommerceDataGuangming.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATACHENGDELOLO = '/api/macro/getEcommerceDataChengDeLolo.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAQIAQIA = '/api/macro/getEcommerceDataQiaqia.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAVVGROUP = '/api/macro/getEcommerceDataVVGroup.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAJINFENGWINE = '/api/macro/getEcommerceDataJinfengWine.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAGUYUELONGSHAN = '/api/macro/getEcommerceDataGuyueLongshan.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATASHANXIFENJIU = '/api/macro/getEcommerceDataShanxiFenjiu.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAZHANGYUA = '/api/macro/getEcommerceDataZhangyuA.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAMOGAO = '/api/macro/getEcommerceDataMogao.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAKEMENNOODLEMFG = '/api/macro/getEcommerceDataKemenNoodleMFG.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAJINZIHAM = '/api/macro/getEcommerceDataJinziHam.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATALOTUS = '/api/macro/getEcommerceDataLotus.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATABEIYINMATE = '/api/macro/getEcommerceDataBeiyinMate.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAQINGDAOHAIER = '/api/macro/getEcommerceDataQingdaoHaier.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATATCLGROUP = '/api/macro/getEcommerceDataTCLGroup.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAMIDEAGROUP = '/api/macro/getEcommerceDataMideaGroup.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAWHIRLPOOL = '/api/macro/getEcommerceDataWhirlpool.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAJOYOUNG = '/api/macro/getEcommerceDataJoyoung.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAVATTI = '/api/macro/getEcommerceDataVatti.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATASUPOR = '/api/macro/getEcommerceDataSupor.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAKONKA = '/api/macro/getEcommerceDataKonka.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATACHANGHONG = '/api/macro/getEcommerceDataChanghong.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATALITTLESWAN = '/api/macro/getEcommerceDataLittleSwan.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAMEILING = '/api/macro/getEcommerceDataMeiling.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAZTE = '/api/macro/getEcommerceDataZTE.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATADATANGTELECOM = '/api/macro/getEcommerceDataDatangTelecom.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATABIRD = '/api/macro/getEcommerceDataBird.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATADAHUATECHNOLOGY = '/api/macro/getEcommerceDataDahuaTechnology.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATATSINGHUATONGFANG = '/api/macro/getEcommerceDataTsinghuaTongfang.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAHEDY = '/api/macro/getEcommerceDataHedy.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAHADAY = '/api/macro/getEcommerceDataHaday.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAYANJINGBEER = '/api/macro/getEcommerceDataYanjingBeer.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAMAIQUER = '/api/macro/getEcommerceDataMaiquer.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATACITICGUOANWINE = '/api/macro/getEcommerceDataCiticGuoanWine.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAQINGQINGBARLEYWINE = '/api/macro/getEcommerceDataQingqingBarleyWine.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAHAOXIANGNI = '/api/macro/getEcommerceDataHaoxiangni.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAFULINGZHACAI = '/api/macro/getEcommerceDataFulingZhacai.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAHUANGSHANGHUANG = '/api/macro/getEcommerceDataHuangshanghuang.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAHAINANYEDAO = '/api/macro/getEcommerceDataHainanYedao.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATASHUANGTAFOOD = '/api/macro/getEcommerceDataShuangtaFood.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAJIUGUILIQUOR = '/api/macro/getEcommerceDataJiuguiLiquor.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATABLACKSESAME = '/api/macro/getEcommerceDataBlackSesame.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAKINGSLUCK = '/api/macro/getEcommerceDataKingsLuck.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATALAOBAIGANLIQUOR = '/api/macro/getEcommerceDataLaobaiganLiquor.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATASHUANGHUIDVPT = '/api/macro/getEcommerceDataShuanghuiDvpt.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    OPT = '/api/options/getOpt.json?contractStatus=%s&optID=%s&secID=%s&ticker=%s&varSecID=%s&varticker=%s&field=%s'.freeze
    MKTOPTD = '/api/market/getMktOptd.json?optID=%s&secID=%s&ticker=%s&tradeDate=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SOCIALDATAXQ = '/api/subject/getSocialDataXQ.json?beginDate=%s&endDate=%s&ticker=%s&field=%s'.freeze
    SOCIALDATAXQBYTICKER = '/api/subject/getSocialDataXQByTicker.json?ticker=%s&field=%s'.freeze
    SOCIALDATAXQBYDATE = '/api/subject/getSocialDataXQByDate.json?statisticsDate=%s&field=%s'.freeze
    OPTVAR = '/api/options/getOptVar.json?exchangeCD=%s&secID=%s&ticker=%s&contractType=%s&exerType=%s&field=%s'.freeze
    NEWSINFO = '/api/subject/getNewsInfo.json?newsID=%s&field=%s'.freeze
    NEWSINFOBYTIME = '/api/subject/getNewsInfoByTime.json?newsPublishDate=%s&beginTime=%s&endTime=%s&field=%s'.freeze
    NEWSCONTENT = '/api/subject/getNewsContent.json?newsID=%s&field=%s'.freeze
    NEWSCONTENTBYTIME = '/api/subject/getNewsContentByTime.json?newsPublishDate=%s&beginTime=%s&endTime=%s&field=%s'.freeze
    COMPANYBYNEWS = '/api/subject/getCompanyByNews.json?newsID=%s&field=%s'.freeze
    NEWSBYCOMPANY = '/api/subject/getNewsByCompany.json?partyID=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    TICKERSBYNEWS = '/api/subject/getTickersByNews.json?newsID=%s&field=%s'.freeze
    NEWSBYTICKERS = '/api/subject/getNewsByTickers.json?secID=%s&secShortName=%s&ticker=%s&beginDate=%s&endDate=%s&exchangeCD=%s&field=%s'.freeze
    MKTEQUDADJ = '/api/market/getMktEqudAdj.json?secID=%s&ticker=%s&tradeDate=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MKTADJF = '/api/market/getMktAdjf.json?secID=%s&ticker=%s&field=%s'.freeze
    OPTIONTICKRTSNAPSHOT = '/api/market/getOptionTickRTSnapshot.json?optionId=%s&field=%s'.freeze
    FUTUREBARRTINTRADAY = '/api/market/getFutureBarRTIntraDay.json?instrumentID=%s&endTime=%s&startTime=%s&field=%s'.freeze
    MKTFUTDVOL = '/api/market/getMktFutdVol.json?secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    THEMESCONTENT = '/api/subject/getThemesContent.json?isMain=%s&themeID=%s&themeName=%s&themeSource=%s&field=%s'.freeze
    TICKERSBYTHEMES = '/api/subject/getTickersByThemes.json?themeID=%s&themeName=%s&beginDate=%s&endDate=%s&isNew=%s&field=%s'.freeze
    THEMESTICKERSINSERT = '/api/subject/getThemesTickersInsert.json?themeID=%s&themeName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    THEMESTICKERSDELETE = '/api/subject/getThemesTickersDelete.json?themeID=%s&themeName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    THEMESBYTICKERS = '/api/subject/getThemesByTickers.json?secID=%s&secShortName=%s&ticker=%s&beginDate=%s&endDate=%s&exchangeCD=%s&field=%s'.freeze
    THEMESPERIOD = '/api/subject/getThemesPeriod.json?isLatest=%s&themeID=%s&themeName=%s&field=%s'.freeze
    ACTIVETHEMES = '/api/subject/getActiveThemes.json?date=%s&field=%s'.freeze
    THEMESSIMILARITY = '/api/subject/getThemesSimilarity.json?themeID=%s&themeName=%s&field=%s'.freeze
    THEMESHEAT = '/api/subject/getThemesHeat.json?themeID=%s&themeName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    SECTORTHEMESBYTICKERS = '/api/subject/getSectorThemesByTickers.json?secID=%s&secShortName=%s&ticker=%s&beginDate=%s&endDate=%s&exchangeCD=%s&field=%s'.freeze
    WEBTHEMESBYTICKERS = '/api/subject/getWebThemesByTickers.json?secID=%s&secShortName=%s&ticker=%s&beginDate=%s&endDate=%s&exchangeCD=%s&field=%s'.freeze
    MKTEQUDLATELY = '/api/market/getMktEqudLately.json?field=%s'.freeze
    FDMTISLATELY = '/api/fundamental/getFdmtISLately.json?field=%s'.freeze
    NEWSHEATINDEX = '/api/subject/getNewsHeatIndex.json?beginDate=%s&endDate=%s&exchangeCD=%s&secID=%s&secShortName=%s&ticker=%s&field=%s'.freeze
    NEWSSENTIMENTINDEX = '/api/subject/getNewsSentimentIndex.json?beginDate=%s&endDate=%s&exchangeCD=%s&secID=%s&secShortName=%s&ticker=%s&field=%s'.freeze
    SECTYPEREL = '/api/master/getSecTypeRel.json?secID=%s&ticker=%s&typeID=%s&field=%s'.freeze
    REPORTBYTICKER = '/api/subject/getReportByTicker.json?ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    REPORTBYCATEGORY = '/api/subject/getReportByCategory.json?beginDate=%s&Category=%s&endDate=%s&field=%s'.freeze
    REPORTCONTENT = '/api/subject/getReportContent.json?ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    MKTLIMIT = '/api/market/getMktLimit.json?secID=%s&ticker=%s&tradeDate=%s&field=%s'.freeze
    ECOMMERCEDATAWULIANGYE = '/api/macro/getEcommerceDataWuliangye.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAGREE = '/api/macro/getEcommerceDataGree.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAHISENSEELECTRIC = '/api/macro/getEcommerceDataHisenseElectric.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAHISENSE = '/api/macro/getEcommerceDataHisense.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAJIAJIAFOOD = '/api/macro/getEcommerceDataJiajiaFood.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAROBAM = '/api/macro/getEcommerceDataRobam.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAASD = '/api/macro/getEcommerceDataASD.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAMACRO = '/api/macro/getEcommerceDataMacro.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAELECPRO = '/api/macro/getEcommerceDataElecpro.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATASANGLEJIN = '/api/macro/getEcommerceDataSanglejin.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAHOMA = '/api/macro/getEcommerceDataHoma.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATALONGDAMEAT = '/api/macro/getEcommerceDataLongdaMeat.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATABYHEALTH = '/api/macro/getEcommerceDataByHealth.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAHAIXIN = '/api/macro/getEcommerceDataHaixin.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAVANWARD = '/api/macro/getEcommerceDataVanward.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAMEIDA = '/api/macro/getEcommerceDataMeida.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAHENGSHUNVINEGARINDUSTRY = '/api/macro/getEcommerceDataHengshunVinegarindustry.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATASHUIJINGFANG = '/api/macro/getEcommerceDataShuijingfang.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATACHUNLAN = '/api/macro/getEcommerceDataChunlan.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAYILITE = '/api/macro/getEcommerceDataYilite.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAHUANGSHI = '/api/macro/getEcommerceDataHuangshi.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAYANGHE = '/api/macro/getEcommerceDataYanghe.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATASANYUAN = '/api/macro/getEcommerceDataSanyuan.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATATUOPAISHEDE = '/api/macro/getEcommerceDataTuopaiShede.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAKUAIJISHAN = '/api/macro/getEcommerceDataKuaijishan.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATATONGHUA = '/api/macro/getEcommerceDataTonghua.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAKWEICHOWMOUTAIGROUP = '/api/macro/getEcommerceDataKweichowMoutaiGroup.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATATSINGTAO = '/api/macro/getEcommerceDataTsingTao.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ACTIVETHEMESINSERT = '/api/subject/getActiveThemesInsert.json?beginDate=%s&endDate=%s&isLatest=%s&themeSource=%s&field=%s'.freeze
    ACTIVETHEMESDELETE = '/api/subject/getActiveThemesDelete.json?beginDate=%s&endDate=%s&isLatest=%s&themeSource=%s&field=%s'.freeze
    EQUINFO = '/api/master/getEquInfo.json?ticker=%s&field=%s'.freeze
    SECTIPS = '/api/market/getSecTips.json?tipsTypeCD=%s&field=%s'.freeze
    THEMESCLUSTER = '/api/subject/getThemesCluster.json?isMain=%s&themeID=%s&themeName=%s&field=%s'.freeze
    THEMESBYNEWS = '/api/subject/getThemesByNews.json?insertDate=%s&newsID=%s&beginTime=%s&endTime=%s&field=%s'.freeze
    BARRTINTRADAYONEMINUTE = '/api/market/getBarRTIntraDayOneMinute.json?time=%s&field=%s'.freeze
    EQURTRANK = '/api/market/getEquRTRank.json?desc=%s&exchangeCD=%s&field=%s'.freeze
    ECOMMERCEDATAGUJING = '/api/macro/getEcommerceDataGujing.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATALUZHOULAOJIAO = '/api/macro/getEcommerceDataLuzhouLaojiao.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATASHANGHAIMALING = '/api/macro/getEcommerceDataShanghaiMaling.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATABLACKCATTLEFOOD = '/api/macro/getEcommerceDataBlackCattleFood.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATADELISI = '/api/macro/getEcommerceDataDelisi.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATASTARLAKEBIOSCIENCE = '/api/macro/getEcommerceDataStarLakeBioscience.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAJONJEEHITECH = '/api/macro/getEcommerceDataJonjeeHiTech.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATACRSANJIU = '/api/macro/getEcommerceDataCRSanjiu.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAJIUZHITANG = '/api/macro/getEcommerceDataJiuzhitang.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAFUANNA = '/api/macro/getEcommerceDataFuanna.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATALUOLAI = '/api/macro/getEcommerceDataLuolai.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAGUIRENNIAO = '/api/macro/getEcommerceDataGuirenniao.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATABAOXINIAO = '/api/macro/getEcommerceDataBaoxiniao.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATALAOFENGXIANG = '/api/macro/getEcommerceDataLaofengxiang.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAFIYTAA = '/api/macro/getEcommerceDataFiytaA.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAGOLDLEAFJEWELRY = '/api/macro/getEcommerceDataGoldleafJewelry.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATACOMIXGROUP = '/api/macro/getEcommerceDataComixGroup.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAYAOJIPLAYINGCARD = '/api/macro/getEcommerceDataYaojiPlayingCard.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAMGSTATIONERY = '/api/macro/getEcommerceDataMGStationery.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATACS = '/api/macro/getEcommerceDataCS.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAEDIFIER = '/api/macro/getEcommerceDataEdifier.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAHIKVISION = '/api/macro/getEcommerceDataHikVision.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATASOLAREAST = '/api/macro/getEcommerceDataSolareast.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATACHIGO = '/api/macro/getEcommerceDataChigo.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    ECOMMERCEDATAAUCMA = '/api/macro/getEcommerceDataAucma.json?indicID=%s&indicName=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    THEMESBYNEWSCOMPANYREL = '/api/subject/getThemesByNewsCompanyRel.json?insertDate=%s&newsID=%s&beginTime=%s&endTime=%s&field=%s'.freeze
    THEMESINSERTDB = '/api/subject/getThemesInsertDB.json?beginDate=%s&endDate=%s&themeSource=%s&field=%s'.freeze
    THEMESBYNEWSLF = '/api/subject/getThemesByNewsLF.json?insertDate=%s&newsID=%s&beginTime=%s&endTime=%s&field=%s'.freeze
    THEMESBYNEWSMF = '/api/subject/getThemesByNewsMF.json?insertDate=%s&newsID=%s&beginTime=%s&endTime=%s&field=%s'.freeze
    INDUSTRYTICKRTSNAPSHOT = '/api/market/getIndustryTickRTSnapshot.json?securityID=%s&field=%s'.freeze
    NEWSINFOBYINSERTTIME = '/api/subject/getNewsInfoByInsertTime.json?newsInsertDate=%s&beginTime=%s&endTime=%s&field=%s'.freeze
    NEWSCONTENTBYINSERTTIME = '/api/subject/getNewsContentByInsertTime.json?newsInsertDate=%s&beginTime=%s&endTime=%s&field=%s'.freeze
    SECTYPEREGIONREL = '/api/master/getSecTypeRegionRel.json?secID=%s&ticker=%s&typeID=%s&field=%s'.freeze
    SECTYPE = '/api/master/getSecType.json?field=%s'.freeze
    SECTYPEREGION = '/api/master/getSecTypeRegion.json?field=%s'.freeze
    SOCIALDATAGUBA = '/api/subject/getSocialDataGuba.json?beginDate=%s&endDate=%s&ticker=%s&field=%s'.freeze
    SOCIALTHEMEDATAGUBA = '/api/subject/getSocialThemeDataGuba.json?beginDate=%s&endDate=%s&themeID=%s&field=%s'.freeze
    FUNDSHARESCHG = '/api/fund/getFundSharesChg.json?secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    THEMESBYNEWSTIME = '/api/subject/getThemesByNewsTime.json?publishBeginTime=%s&publishEndTime=%s&field=%s'.freeze
    THEMESBYNEWSTIMECOMPANYREL = '/api/subject/getThemesByNewsTimeCompanyRel.json?publishBeginTime=%s&publishEndTime=%s&field=%s'.freeze
    THEMESBYNEWSTIMELF = '/api/subject/getThemesByNewsTimeLF.json?publishBeginTime=%s&publishEndTime=%s&field=%s'.freeze
    THEMESBYNEWSTIMEMF = '/api/subject/getThemesByNewsTimeMF.json?publishBeginTime=%s&publishEndTime=%s&field=%s'.freeze
    MKTFUNDDADJAF = '/api/market/getMktFunddAdjAf.json?secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    REPORTCONTENTBYID = '/api/subject/getReportContentByID.json?reportID=%s&field=%s'.freeze
    THEMESBYNEWS2 = '/api/subject/getThemesByNews2.json?insertBeginTime=%s&insertEndTime=%s&newsID=%s&field=%s'.freeze
    THEMESBYNEWSTIME2 = '/api/subject/getThemesByNewsTime2.json?publishBeginTime=%s&publishEndTime=%s&field=%s'.freeze
    SYSCODE = '/api/master/getSysCode.json?codeTypeID=%s&valueCD=%s&field=%s'.freeze
    FUNDLEVERAGEINFO = '/api/fund/getFundLeverageInfo.json?exchangeCDLeverage=%s&secID=%s&ticker=%s&field=%s'.freeze
    SECST = '/api/equity/getSecST.json?secID=%s&ticker=%s&beginDate=%s&endDate=%s&field=%s'.freeze
    DERIV = '/api/IV/getDerIv.json?beginDate=%s&endDate=%s&optID=%s&SecID=%s&field=%s'.freeze
    DERIVHV = '/api/IV/getDerIvHv.json?beginDate=%s&endDate=%s&SecID=%s&period=%s&field=%s'.freeze
    DERIVINDEX = '/api/IV/getDerIvIndex.json?beginDate=%s&endDate=%s&SecID=%s&period=%s&field=%s'.freeze
    DERIVIVPDELTA = '/api/IV/getDerIvIvpDelta.json?beginDate=%s&endDate=%s&SecID=%s&delta=%s&period=%s&field=%s'.freeze
    DERIVPARAM = '/api/IV/getDerIvParam.json?beginDate=%s&endDate=%s&SecID=%s&expDate=%s&field=%s'.freeze
    DERIVRAWDELTA = '/api/IV/getDerIvRawDelta.json?beginDate=%s&endDate=%s&SecID=%s&delta=%s&period=%s&field=%s'.freeze
    DERIVSURFACE = '/api/IV/getDerIvSurface.json?beginDate=%s&endDate=%s&SecID=%s&contractType=%s&field=%s'.freeze
  end
end
